# Generated by Django 4.1.2 on 2022-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='black-profile-picture', upload_to='profile_images'),
        ),
    ]
